BEGIN;

-- ---------------------------------------------------------------------------
-- Stripe billing and merchant payments foundation.
--
-- Purpose:
-- - separate tenant SaaS billing from tenant merchant payments
-- - add durable event storage for webhook-driven processing
-- - add current-state tables for fast reads and entitlement sync
--
-- Notes:
-- - designed for PostgreSQL on backend-rc
-- - idempotent where practical
-- - avoids assumptions about order/booking table names by storing foreign ids
-- ---------------------------------------------------------------------------

-- 1) Tenant billing profile: platform Stripe Billing state
CREATE TABLE IF NOT EXISTS public.tenant_billing_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  stripe_customer_id TEXT NOT NULL,
  stripe_subscription_id TEXT,
  billing_email TEXT,
  plan_phase_key TEXT NOT NULL DEFAULT 'phase_base' CHECK (
    plan_phase_key IN ('phase_base', 'phase_growth', 'phase_scale')
  ),
  billing_cycle TEXT NOT NULL DEFAULT 'monthly' CHECK (
    billing_cycle IN ('monthly', 'annual')
  ),
  subscription_status TEXT NOT NULL DEFAULT 'inactive' CHECK (
    subscription_status IN (
      'inactive',
      'trialing',
      'active',
      'past_due',
      'unpaid',
      'canceled',
      'incomplete',
      'incomplete_expired'
    )
  ),
  grace_until TIMESTAMPTZ,
  current_period_start TIMESTAMPTZ,
  current_period_end TIMESTAMPTZ,
  cancel_at_period_end BOOLEAN NOT NULL DEFAULT FALSE,
  last_invoice_id TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  sync_status TEXT NOT NULL DEFAULT 'ok' CHECK (
    sync_status IN ('ok', 'degraded', 'failed')
  ),
  last_synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id),
  UNIQUE (stripe_customer_id),
  UNIQUE (stripe_subscription_id)
);

CREATE INDEX IF NOT EXISTS idx_tenant_billing_profiles_status
  ON public.tenant_billing_profiles (subscription_status);

CREATE INDEX IF NOT EXISTS idx_tenant_billing_profiles_plan_phase
  ON public.tenant_billing_profiles (plan_phase_key);

CREATE INDEX IF NOT EXISTS idx_tenant_billing_profiles_sync_status
  ON public.tenant_billing_profiles (sync_status);

-- 2) Tenant billing add-ons: current recurring add-on state
CREATE TABLE IF NOT EXISTS public.tenant_billing_addons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  addon_key TEXT NOT NULL CHECK (
    addon_key IN (
      'google_business_management',
      'sms_leads_and_comms',
      'google_ads_optimization',
      'custom_ai_agent'
    )
  ),
  stripe_subscription_item_id TEXT,
  stripe_price_id TEXT,
  status TEXT NOT NULL DEFAULT 'inactive' CHECK (
    status IN ('inactive', 'active', 'scheduled_cancel', 'canceled')
  ),
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  current_period_start TIMESTAMPTZ,
  current_period_end TIMESTAMPTZ,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id, addon_key),
  UNIQUE (stripe_subscription_item_id)
);

CREATE INDEX IF NOT EXISTS idx_tenant_billing_addons_status
  ON public.tenant_billing_addons (status);

-- 3) Tenant payment account: connected-account merchant payment state
CREATE TABLE IF NOT EXISTS public.tenant_payment_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  stripe_connected_account_id TEXT NOT NULL,
  account_type TEXT NOT NULL DEFAULT 'express' CHECK (
    account_type IN ('standard', 'express', 'custom')
  ),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (
    status IN ('pending', 'active', 'restricted', 'disabled')
  ),
  charges_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  payouts_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  details_submitted BOOLEAN NOT NULL DEFAULT FALSE,
  onboarding_completed_at TIMESTAMPTZ,
  default_currency CHAR(3) NOT NULL DEFAULT 'USD',
  country CHAR(2),
  capabilities_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  requirements_due_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  last_synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id),
  UNIQUE (stripe_connected_account_id)
);

CREATE INDEX IF NOT EXISTS idx_tenant_payment_accounts_status
  ON public.tenant_payment_accounts (status);

CREATE INDEX IF NOT EXISTS idx_tenant_payment_accounts_capabilities
  ON public.tenant_payment_accounts (charges_enabled, payouts_enabled);

-- 4) Durable Stripe event ledger for both platform billing and connected accounts
CREATE TABLE IF NOT EXISTS public.billing_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id TEXT NOT NULL,
  stripe_account_scope TEXT NOT NULL CHECK (
    stripe_account_scope IN ('platform', 'connected')
  ),
  stripe_account_id TEXT,
  tenant_id BIGINT REFERENCES public.tenants(id) ON DELETE SET NULL,
  source TEXT NOT NULL CHECK (
    source IN ('stripe_webhook', 'reconcile_job', 'manual_replay')
  ),
  event_type TEXT NOT NULL,
  api_version TEXT,
  livemode BOOLEAN NOT NULL DEFAULT FALSE,
  payload JSONB NOT NULL,
  payload_digest TEXT,
  status TEXT NOT NULL DEFAULT 'received' CHECK (
    status IN ('received', 'queued', 'processing', 'processed', 'failed', 'dead_lettered', 'ignored')
  ),
  failure_code TEXT,
  failure_message TEXT,
  retry_count INTEGER NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
  first_received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  processed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_billing_events_event_scope_account
  ON public.billing_events (event_id, stripe_account_scope, COALESCE(stripe_account_id, 'platform'));

CREATE INDEX IF NOT EXISTS idx_billing_events_status_created
  ON public.billing_events (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_billing_events_tenant_created
  ON public.billing_events (tenant_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_billing_events_type_created
  ON public.billing_events (event_type, created_at DESC);

-- 5) Fast-read entitlement snapshot derived from platform billing
CREATE TABLE IF NOT EXISTS public.tenant_entitlement_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  plan_phase_key TEXT NOT NULL CHECK (
    plan_phase_key IN ('phase_base', 'phase_growth', 'phase_scale')
  ),
  addon_keys JSONB NOT NULL DEFAULT '[]'::jsonb,
  effective_modules JSONB NOT NULL DEFAULT '[]'::jsonb,
  effective_features JSONB NOT NULL DEFAULT '[]'::jsonb,
  feature_limits JSONB NOT NULL DEFAULT '{}'::jsonb,
  entitlement_state TEXT NOT NULL DEFAULT 'active' CHECK (
    entitlement_state IN ('active', 'grace', 'restricted', 'suspended')
  ),
  reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
  source_event_id TEXT,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  computed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id)
);

CREATE INDEX IF NOT EXISTS idx_tenant_entitlement_snapshots_state
  ON public.tenant_entitlement_snapshots (entitlement_state);

-- 6) Auditable override records
CREATE TABLE IF NOT EXISTS public.tenant_entitlement_overrides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  override_type TEXT NOT NULL CHECK (
    override_type IN ('grant', 'restrict', 'suspend', 'grace_extension')
  ),
  override_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  reason TEXT,
  starts_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ends_at TIMESTAMPTZ,
  created_by BIGINT REFERENCES public."user"(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tenant_entitlement_overrides_tenant_window
  ON public.tenant_entitlement_overrides (tenant_id, starts_at, ends_at);

-- 7) Ecommerce payment records
CREATE TABLE IF NOT EXISTS public.tenant_order_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  website_id BIGINT,
  order_id BIGINT,
  stripe_account_id TEXT NOT NULL,
  stripe_checkout_session_id TEXT,
  stripe_payment_intent_id TEXT,
  stripe_charge_id TEXT,
  amount_cents BIGINT NOT NULL CHECK (amount_cents >= 0),
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  status TEXT NOT NULL CHECK (
    status IN ('pending', 'succeeded', 'failed', 'refunded', 'partially_refunded', 'disputed', 'canceled')
  ),
  payment_purpose TEXT NOT NULL DEFAULT 'ecommerce_order' CHECK (
    payment_purpose = 'ecommerce_order'
  ),
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (stripe_checkout_session_id),
  UNIQUE (stripe_payment_intent_id),
  UNIQUE (stripe_charge_id)
);

CREATE INDEX IF NOT EXISTS idx_tenant_order_payments_tenant_created
  ON public.tenant_order_payments (tenant_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_tenant_order_payments_order
  ON public.tenant_order_payments (order_id);

CREATE INDEX IF NOT EXISTS idx_tenant_order_payments_status
  ON public.tenant_order_payments (status);

-- 8) Appointment payment records with deposit and balance support
CREATE TABLE IF NOT EXISTS public.tenant_booking_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  website_id BIGINT,
  booking_id BIGINT,
  stripe_account_id TEXT NOT NULL,
  stripe_checkout_session_id TEXT,
  stripe_payment_intent_id TEXT,
  stripe_charge_id TEXT,
  payment_purpose TEXT NOT NULL CHECK (
    payment_purpose IN ('appointment_deposit', 'appointment_balance')
  ),
  amount_cents BIGINT NOT NULL CHECK (amount_cents >= 0),
  deposit_amount_cents BIGINT,
  remaining_amount_cents BIGINT,
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  status TEXT NOT NULL CHECK (
    status IN ('pending', 'succeeded', 'failed', 'refunded', 'partially_refunded', 'disputed', 'canceled')
  ),
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (stripe_checkout_session_id),
  UNIQUE (stripe_payment_intent_id),
  UNIQUE (stripe_charge_id)
);

CREATE INDEX IF NOT EXISTS idx_tenant_booking_payments_tenant_created
  ON public.tenant_booking_payments (tenant_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_tenant_booking_payments_booking
  ON public.tenant_booking_payments (booking_id);

CREATE INDEX IF NOT EXISTS idx_tenant_booking_payments_status
  ON public.tenant_booking_payments (status);

COMMIT;