BEGIN;

-- ---------------------------------------------------------------------------
-- Phase 1: Tenant foundation schema for local PostgreSQL first, then RDS.
-- This script is idempotent where practical and designed to minimize risk.
-- ---------------------------------------------------------------------------

-- 1) Core tenant table
CREATE TABLE IF NOT EXISTS public.tenants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_website_id BIGINT UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  business_type TEXT NOT NULL DEFAULT 'lead_gen_services' CHECK (
    business_type IN (
      'lead_gen_services',
      'appointments',
      'ecommerce',
      'reservations',
      'hybrid_local'
    )
  ),
  status TEXT NOT NULL DEFAULT 'active' CHECK (
    status IN ('active', 'inactive', 'suspended')
  ),
  default_currency CHAR(3) NOT NULL DEFAULT 'USD',
  timezone TEXT NOT NULL DEFAULT 'America/Chicago',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tenants_status ON public.tenants(status);
CREATE INDEX IF NOT EXISTS idx_tenants_business_type ON public.tenants(business_type);

-- 2) Domain mapping per tenant
CREATE TABLE IF NOT EXISTS public.tenant_domains (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  domain TEXT NOT NULL,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (
    status IN ('pending', 'active', 'inactive', 'verification_failed')
  ),
  verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tenant_domains_domain_ci
  ON public.tenant_domains (LOWER(domain));

CREATE UNIQUE INDEX IF NOT EXISTS uq_tenant_domains_one_active_primary
  ON public.tenant_domains (tenant_id)
  WHERE is_primary = TRUE AND status = 'active';

CREATE INDEX IF NOT EXISTS idx_tenant_domains_tenant_status
  ON public.tenant_domains (tenant_id, status);

-- 3) User-to-tenant role assignments
CREATE TABLE IF NOT EXISTS public.user_tenant_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES public."user"(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (
    role IN (
      'platform_admin',
      'tenant_owner',
      'tenant_manager',
      'tenant_editor',
      'tenant_viewer',
      'support_agent'
    )
  ),
  status TEXT NOT NULL DEFAULT 'active' CHECK (
    status IN ('active', 'inactive')
  ),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id, user_id, role)
);

CREATE INDEX IF NOT EXISTS idx_user_tenant_roles_user_id
  ON public.user_tenant_roles (user_id);

CREATE INDEX IF NOT EXISTS idx_user_tenant_roles_tenant_id
  ON public.user_tenant_roles (tenant_id);

-- 4) Tenant modules (for module-level enablement)
CREATE TABLE IF NOT EXISTS public.tenant_modules (
  tenant_id BIGINT NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  module_key TEXT NOT NULL CHECK (
    module_key IN (
      'website_core',
      'seo_content',
      'lead_capture',
      'calendar_appointments',
      'checkout_ecommerce',
      'reservations',
      'google_business_management',
      'sms_leads_and_comms',
      'google_ads_optimization',
      'custom_ai_agent'
    )
  ),
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  source TEXT NOT NULL DEFAULT 'system_default' CHECK (
    source IN ('system_default', 'plan', 'addon', 'manual_override')
  ),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (tenant_id, module_key)
);

CREATE INDEX IF NOT EXISTS idx_tenant_modules_enabled
  ON public.tenant_modules (enabled);

-- 5) Tenant feature flags / entitlements
CREATE TABLE IF NOT EXISTS public.tenant_features (
  tenant_id BIGINT NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  feature_key TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  config JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (tenant_id, feature_key)
);

CREATE INDEX IF NOT EXISTS idx_tenant_features_enabled
  ON public.tenant_features (enabled);

-- 6) Backfill tenants from existing website records
INSERT INTO public.tenants (id, legacy_website_id, slug, name, business_type, status, created_at, updated_at)
SELECT
  w.id,
  w.id,
  COALESCE(NULLIF(REGEXP_REPLACE(LOWER(COALESCE(w.name, '')), '[^a-z0-9]+', '-', 'g'), ''), 'tenant-' || w.id::text),
  COALESCE(w.name, 'Tenant ' || w.id::text),
  'lead_gen_services',
  'active',
  COALESCE(w.created_at::timestamptz, NOW()),
  NOW()
FROM public.website w
ON CONFLICT (id) DO NOTHING;

-- Keep tenants identity sequence in sync after explicit id inserts.
SELECT setval(
  pg_get_serial_sequence('public.tenants', 'id'),
  COALESCE((SELECT MAX(id) FROM public.tenants), 1),
  TRUE
);

-- 7) Backfill domain rows from existing website.domain values
INSERT INTO public.tenant_domains (tenant_id, domain, is_primary, status, verified_at)
SELECT
  t.id,
  w.domain,
  TRUE,
  'active',
  NOW()
FROM public.website w
JOIN public.tenants t
  ON t.legacy_website_id = w.id
WHERE w.domain IS NOT NULL
  AND BTRIM(w.domain) <> ''
ON CONFLICT DO NOTHING;

-- 8) Add tenant_id columns to current tenant-owned tables and backfill from website_id
ALTER TABLE IF EXISTS public.asset ADD COLUMN IF NOT EXISTS tenant_id BIGINT;
ALTER TABLE IF EXISTS public.blog_post ADD COLUMN IF NOT EXISTS tenant_id BIGINT;
ALTER TABLE IF EXISTS public.business_listing ADD COLUMN IF NOT EXISTS tenant_id BIGINT;
ALTER TABLE IF EXISTS public.detail_slug ADD COLUMN IF NOT EXISTS tenant_id BIGINT;
ALTER TABLE IF EXISTS public.location_local ADD COLUMN IF NOT EXISTS tenant_id BIGINT;
ALTER TABLE IF EXISTS public.page ADD COLUMN IF NOT EXISTS tenant_id BIGINT;
ALTER TABLE IF EXISTS public.page_category ADD COLUMN IF NOT EXISTS tenant_id BIGINT;
ALTER TABLE IF EXISTS public.service ADD COLUMN IF NOT EXISTS tenant_id BIGINT;
ALTER TABLE IF EXISTS public.stripe_customer ADD COLUMN IF NOT EXISTS tenant_id BIGINT;
ALTER TABLE IF EXISTS public."user" ADD COLUMN IF NOT EXISTS tenant_id BIGINT;

UPDATE public.asset SET tenant_id = website_id WHERE tenant_id IS NULL AND website_id IS NOT NULL;
UPDATE public.blog_post SET tenant_id = website_id WHERE tenant_id IS NULL AND website_id IS NOT NULL;
UPDATE public.business_listing SET tenant_id = website_id WHERE tenant_id IS NULL AND website_id IS NOT NULL;
UPDATE public.detail_slug SET tenant_id = website_id WHERE tenant_id IS NULL AND website_id IS NOT NULL;
UPDATE public.location_local SET tenant_id = website_id WHERE tenant_id IS NULL AND website_id IS NOT NULL;
UPDATE public.page SET tenant_id = website_id WHERE tenant_id IS NULL AND website_id IS NOT NULL;
UPDATE public.page_category SET tenant_id = website_id WHERE tenant_id IS NULL AND website_id IS NOT NULL;
UPDATE public.service SET tenant_id = website_id WHERE tenant_id IS NULL AND website_id IS NOT NULL;
UPDATE public.stripe_customer SET tenant_id = website_id WHERE tenant_id IS NULL AND website_id IS NOT NULL;
UPDATE public."user" SET tenant_id = website_id WHERE tenant_id IS NULL AND website_id IS NOT NULL;

-- Add FKs as NOT VALID first to reduce lock/scan impact, then validate.
ALTER TABLE IF EXISTS public.asset
  ADD CONSTRAINT IF NOT EXISTS asset_tenant_id_fkey
  FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE SET NULL NOT VALID;

ALTER TABLE IF EXISTS public.blog_post
  ADD CONSTRAINT IF NOT EXISTS blog_post_tenant_id_fkey
  FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE SET NULL NOT VALID;

ALTER TABLE IF EXISTS public.business_listing
  ADD CONSTRAINT IF NOT EXISTS business_listing_tenant_id_fkey
  FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE SET NULL NOT VALID;

ALTER TABLE IF EXISTS public.detail_slug
  ADD CONSTRAINT IF NOT EXISTS detail_slug_tenant_id_fkey
  FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE SET NULL NOT VALID;

ALTER TABLE IF EXISTS public.location_local
  ADD CONSTRAINT IF NOT EXISTS location_local_tenant_id_fkey
  FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE SET NULL NOT VALID;

ALTER TABLE IF EXISTS public.page
  ADD CONSTRAINT IF NOT EXISTS page_tenant_id_fkey
  FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE SET NULL NOT VALID;

ALTER TABLE IF EXISTS public.page_category
  ADD CONSTRAINT IF NOT EXISTS page_category_tenant_id_fkey
  FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE SET NULL NOT VALID;

ALTER TABLE IF EXISTS public.service
  ADD CONSTRAINT IF NOT EXISTS service_tenant_id_fkey
  FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE SET NULL NOT VALID;

ALTER TABLE IF EXISTS public.stripe_customer
  ADD CONSTRAINT IF NOT EXISTS stripe_customer_tenant_id_fkey
  FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE SET NULL NOT VALID;

ALTER TABLE IF EXISTS public."user"
  ADD CONSTRAINT IF NOT EXISTS user_tenant_id_fkey
  FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE SET NULL NOT VALID;

ALTER TABLE IF EXISTS public.asset VALIDATE CONSTRAINT asset_tenant_id_fkey;
ALTER TABLE IF EXISTS public.blog_post VALIDATE CONSTRAINT blog_post_tenant_id_fkey;
ALTER TABLE IF EXISTS public.business_listing VALIDATE CONSTRAINT business_listing_tenant_id_fkey;
ALTER TABLE IF EXISTS public.detail_slug VALIDATE CONSTRAINT detail_slug_tenant_id_fkey;
ALTER TABLE IF EXISTS public.location_local VALIDATE CONSTRAINT location_local_tenant_id_fkey;
ALTER TABLE IF EXISTS public.page VALIDATE CONSTRAINT page_tenant_id_fkey;
ALTER TABLE IF EXISTS public.page_category VALIDATE CONSTRAINT page_category_tenant_id_fkey;
ALTER TABLE IF EXISTS public.service VALIDATE CONSTRAINT service_tenant_id_fkey;
ALTER TABLE IF EXISTS public.stripe_customer VALIDATE CONSTRAINT stripe_customer_tenant_id_fkey;
ALTER TABLE IF EXISTS public."user" VALIDATE CONSTRAINT user_tenant_id_fkey;

-- Tenant-friendly indexes for common filtering patterns
CREATE INDEX IF NOT EXISTS idx_asset_tenant_id ON public.asset(tenant_id);
CREATE INDEX IF NOT EXISTS idx_blog_post_tenant_id ON public.blog_post(tenant_id);
CREATE INDEX IF NOT EXISTS idx_business_listing_tenant_id ON public.business_listing(tenant_id);
CREATE INDEX IF NOT EXISTS idx_detail_slug_tenant_id ON public.detail_slug(tenant_id);
CREATE INDEX IF NOT EXISTS idx_location_local_tenant_id ON public.location_local(tenant_id);
CREATE INDEX IF NOT EXISTS idx_page_tenant_id ON public.page(tenant_id);
CREATE INDEX IF NOT EXISTS idx_page_category_tenant_id ON public.page_category(tenant_id);
CREATE INDEX IF NOT EXISTS idx_service_tenant_id ON public.service(tenant_id);
CREATE INDEX IF NOT EXISTS idx_stripe_customer_tenant_id ON public.stripe_customer(tenant_id);
CREATE INDEX IF NOT EXISTS idx_user_tenant_id ON public."user"(tenant_id);

COMMIT;
